### ISSUE TITLE
 #include <numbers> error

### ISSUE THREAD

**Issue by lingtengqiu** [bernhardmgruber/bpa#2]
maybe it is suitable to Cxx20? but my compiler is cxx17, how can I modify your codes?

**Comment by bernhardmgruber** [comment]
I guess you got a compile error because the `<numbers>` header was not found. This header is available with C++20.

You can backport the code yourself by removing the `#include <numbers>`. If I recall correctly, I use it for `std::numbers::pi`. You can replace that by `M_PI` from `#include <cmath>` on some compilers. Give it a try!
